name: CI

on:
  push:
    branches: [ master ]

jobs:

  test_publish:
    name: Test and Publish
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
      - run: npm install
      - run: npm test
      - run: npm run semantic-release

